### ISSUE TITLE
Cloning the repository

### ISSUE THREAD

**Issue by alanhortz** [nicolasgermeaux/basic-oauth-react#3]
Nicolas, 

Here is an excerpt from the npm install made right after the git clone command.

Development/basic-oauth-react [main] » npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @material-ui/core@4.12.4
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@"^18.0.0" from @testing-library/react@13.3.0
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^13.3.0" from the root project
npm ERR!   5 more (react-dom, react-router, react-router-dom, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"^4.12.4" from the root project
npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
npm ERR!   node_modules/@material-ui/icons
npm ERR!     @material-ui/icons@"^4.11.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR!   node_modules/@material-ui/core
npm ERR!     @material-ui/core@"^4.12.4" from the root project
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
npm ERR!     node_modules/@material-ui/icons
npm ERR!       @material-ui/icons@"^4.11.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/alanhortz/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alanhortz/.npm/_logs/2022-08-02T11_16_05_329Z-debug-0.log
Development/basic-oauth-react [main] » npx install
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alanhortz/.npm/_logs/2022-08-02T11_16_48_812Z-debug-0.log
Development/basic-oauth-react [main] » 

Did you encountered this issue ?

Alan

**Comment by nicolasgermeaux** [comment]
@alanhortz what version of Node do you have? I'm checkin it right now

**Comment by nicolasgermeaux** [comment]
I tried on my local server and had a similar problem. I updated all packages and now it's working. Tell me if it's good for you with my latest push?

**Comment by alanhortz** [comment]
Hi there ! 

I have node version v14.16.0 installed and killed the repo, installed again with `npm install` and it worked although I encountered a warning regarding npm version and lockfileVersion@1


```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

Here is the output of the `npm version` command : 

```json
{
  'react-basic-login': '0.1.0',
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.16.0',
  openssl: '1.1.1j',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}
```

**Comment by alanhortz** [comment]
What is your node version please ? `node --version`

**Comment by nicolasgermeaux** [comment]
Ok I see what's going on - actually I'm working with Node v16 so that's probably the problem here. Anyway is it working now? You'll find the login and password in the README file for testing 20x and 30x response in the auth system

**Comment by alanhortz** [comment]
Totally working, I just want to be aligned on the "dev tool suite" you use, what is the output of both `npm version` and `node version` ?

**Comment by nicolasgermeaux** [comment]
Sure, here it is : 

Node -v : v16.15.1
npm -v : 8.11.0

**Comment by nicolasgermeaux** [comment]
Output of `npm version `

```
{
  'react-basic-login': '0.1.0',
  npm: '8.11.0',
  node: '16.15.1',
  v8: '9.4.146.24-node.21',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1o+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by alanhortz** [comment]
Something's very strange : maybe I have a corrupted install of node through `n` (the node version manager), let's close this one as it seems very related to my setup.
